# Generated by Django 2.0.4 on 2018-04-18 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_auto_20180418_0859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='test',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
