# Generated by Django 2.0.4 on 2018-06-17 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_auto_20180617_0156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_description', models.CharField(max_length=200)),
                ('long_description', models.CharField(max_length=2000)),
            ],
        ),
        migrations.AlterField(
            model_name='test',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.Topic', verbose_name='Тематика'),
        ),
        migrations.AddField(
            model_name='subject',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.Test', verbose_name='Тема'),
        ),
    ]
