# Generated by Django 2.0.4 on 2018-05-05 20:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_auto_20180418_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 5, 20, 58, 59, 694996, tzinfo=utc), verbose_name='date published'),
        ),
    ]
