# Generated by Django 2.0.4 on 2018-07-29 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_auto_20180617_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='tests.Question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='tests.Test'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='tests.Test', verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='test',
            name='icon',
            field=models.FileField(blank=True, upload_to='', verbose_name='test icon'),
        ),
    ]
