# Generated by Django 2.0.4 on 2018-07-30 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_auto_20180729_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='icon',
            field=models.FileField(upload_to='', verbose_name='test icon'),
        ),
    ]
