# Generated by Django 2.0.4 on 2018-05-06 06:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0006_auto_20180505_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 6, 6, 47, 50, 243834, tzinfo=utc), verbose_name='date published'),
        ),
    ]
