# Generated by Django 2.0.4 on 2018-08-05 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0007_auto_20180805_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='icon',
            field=models.FileField(upload_to='', verbose_name='test icon'),
        ),
    ]
