# Generated by Django 2.0.4 on 2018-08-05 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0008_auto_20180805_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='icon',
            field=models.ImageField(upload_to='', verbose_name='topic icon'),
        ),
    ]
