# Generated by Django 2.0.4 on 2018-05-10 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0010_auto_20180510_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='icon',
            field=models.FileField(upload_to='', verbose_name='topic icon'),
        ),
    ]
