# Generated by Django 2.0.4 on 2018-05-10 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0011_auto_20180510_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='icon',
            field=models.FileField(upload_to='', verbose_name='topic icon'),
        ),
    ]
