# Generated by Django 2.0.4 on 2018-05-10 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0012_auto_20180510_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='icon',
            field=models.ImageField(default='', upload_to='', verbose_name='test icon'),
            preserve_default=False,
        ),
    ]
