# Generated by Django 2.0.4 on 2018-05-10 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0013_test_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='icon',
            field=models.FileField(upload_to='', verbose_name='test icon'),
        ),
    ]
